### ISSUE TITLE
Blank message sent over websocket

### ISSUE THREAD

**Issue by go-oleg** [juttle/outrigger#102]
When running a juttle program multiple times, sometimes blank messages come over the websocket from juttled:

![image](https://cloud.githubusercontent.com/assets/3344137/12454161/28a9fdfc-bf4b-11e5-868a-3f833a09b043.png)

juttle:
```
input a: text -label 'what';
emit -limit 1 | put v = 0 | view table;
```

Causes an exception in job-socket.js:

![image](https://cloud.githubusercontent.com/assets/3344137/12454185/44edb45e-bf4b-11e5-9a32-2d2232592298.png)

In my testing, this happens _most_ of the time. May have something to do with the duration between program runs.

From a git bisect, this behavior started happening in 60a60eeaed78bb36de9915612a5fc350eccc6029.

cc @dmehra who discovered this last night while running a more complicated juttle program.

cc @mstemm

**Comment by demmer** [comment]
I saw that yesterday as well. 

-m

**Comment by mstemm** [comment]
Duplicated in juttle-service as juttle/juttle-service#17. Un-assigning this from myself as it's for the old product.
