### ISSUE TITLE
setting display.orientation for barchart results in Uncaught error

### ISSUE THREAD

**Issue by rlgomes** [juttle/outrigger#111]
The juttle I executed was:

```
read stochastic -source 'cdn' -nhosts 10 -from :10 minutes before 2014-01-01: -to :2014-01-01: -source_type 'metrics' name = 'cpu'
| filter name = 'cpu'
| reduce value = avg(value) by host
| sort value -desc
| view barchart -o {
    categoryField: 'host',
    valueField: 'value',
    title: 'Average CPU % per host for last 10 minutes',
    yScales: {
      primary: {
        tickFormat: '%'
      }
    },
    tooltip: {
      valueFormat: '%'
    },
    display: {
        orientation: 'horizontal'
    }
  }
```

without the display.orientation being set this works as expected but with the display orientation set to horizontal or vertical this results in uncaught error with no details.

**Comment by go-oleg** [comment]
The option should be `-orientation` instead of `-display.orientation`. Created https://github.com/juttle/outrigger/issues/112 to track handling and displaying these errors to the user.

**Comment by rlgomes** [comment]
@go-oleg thanks for the error reporting part as that is the one that is really going to help when debugging things.

The `orientation` vs `-display.orientation` wasn't updated in the docs @dmehra.

**Comment by go-oleg** [comment]
@rlgomes I just republished the docs so they should reflect the current state of the world.

**Comment by dmehra** [comment]
ok to close this @rlgomes ?
