### ISSUE TITLE
Outrigger should display errors generated during view instantiation

### ISSUE THREAD

**Issue by go-oleg** [juttle/outrigger#112]
Creating this as a result of https://github.com/juttle/outrigger/issues/111.

When invalid params are passed into views, they throw errors. We should handle these errors appropriately and display them to the user, much like we did for juttle compile and runtime errors for https://github.com/juttle/outrigger/issues/29.

**Comment by demmer** [comment]
I've run into this a bunch of times and it really makes it confusing to know what is happening.

Assuming it's reasonably straightforward to fix this, can we get it in before releasing outrigger 0.4.0? @mnibecker?

**Comment by mstemm** [comment]
Covered by https://github.com/juttle/juttle-viewer/issues/8.
