### ISSUE TITLE
Slim dependencies

### ISSUE THREAD

**Issue by jadbox** [juttle/outrigger#128]
It look two hours on the local network to `npm install` when pulling down outrigger (npm 2.14.7). Offhand, it may be better to remove all the adapters from being hard-coded to outrigger itself and allow projects to inject adapter references in.

**Comment by demmer** [comment]
That's surprising. Installing even with a clean npm cache seems to only take about a minute:

```
# npm cache clean; time npm install outrigger
npm install outrigger  44.06s user 16.55s system 116% cpu 51.818 total
```

I wonder if you ran into a bad network condition or if something happened to be going bad with npm's services at the time you ran this?

**Comment by jadbox** [comment]
Excluding babel, the current install is 102M. The packages pulled down fairly quickly, but there was a ton of intermittent steps for the libraries used in the adapters. Some of them required compiling like the below library: 

Noticed this was slow:
```
make: Entering directory '/home/jdunlap/npm/lib/node_modules/juttle-postgres-adapter/node_modules/juttle/node_modules/node-grok/node_modules/oniguruma/build'
  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
...
```

I'd also recommend moving juttle-client-library (which requires React and a host of browser libs) and any examples out from the Outrigger repo into something like outrigger_example.

**Comment by mstemm** [comment]
We think this was partially related to the bad dns settings within the vm, which would cause most dns lookups to time out on the first resolv.conf entry, adding ~5 seconds to all dns lookups.

Additionally, we've split out juttle-service, which has just the apis to run programs, from the larger juttle-engine, which also contains the app and larger set of dependencies.

Together, this should have solved the problem.
