### ISSUE TITLE
Add client-driven job management

### ISSUE THREAD

**Issue by mstemm** [juttle/outrigger#13]
Currently, outrigger does a good job of handing a single program, managed by the browser given a path.

However, for some use cases (i.e. outrigger running in a docker container, an outrigger that does not share a file system with an editor), it will be useful to have a client program/the editor push program bundles through outrigger to the browser.

This enhancement tracks doing that work. On the client side, outrigger-client supports "push" and "watch" commands that push bundles through the rendezvous channel. We just need to modify the browser side to receive these bundles and run them.

**Comment by mstemm** [comment]
This is done, isn't it?

**Comment by mnibecker** [comment]
Yes resolved by #57. Should be closed.
