### ISSUE TITLE
add a "yes, i am responsive" endpoint at outrigger root

### ISSUE THREAD

**Issue by go-oleg** [juttle/outrigger#130]
Applications using outrigger APIs should have an easy way to confirm an outrigger server is responsive. Additionally, being able to fetch version information for outrigger, and the juttle/adapters it uses would also be useful.

Proposing adding a new endpoint at `/` that returns this information. Hopefully the implementation of getting the version information is fast/trivial enough that this endpoint can double as a simple responsiveness check.

Context:
In exploring building a grafana juttle datasource plugin, it provides hooks to let a user test whether a configured data source is available. We'd use this new endpoint for that.

Example of what Elasticsearch returns at `/` (not that its necessarily the best example):
```json
{
  "name" : "N'Gabthoth",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by mstemm** [comment]
Duplicated as https://github.com/juttle/juttle-service/issues/49.
