### ISSUE TITLE
websocket messages are being dropped

### ISSUE THREAD

**Issue by go-oleg** [juttle/outrigger#131]
There have been some reports of outrigger not showing all the points coming out of a juttle program.

A program to reproduce this:

```
read file -file 'dense.json' -to :2014-01-01T00:59:59:
| keep value1, time
| view timechart -valueField 'value1'
```

The json file (needs to be renamed to .json): [dense.txt](https://github.com/juttle/outrigger/files/111582/dense.txt)

If you run this program, you will get a timechart with the following time range:
![image](https://cloud.githubusercontent.com/assets/3344137/12706114/8b8d3944-c832-11e5-8267-f4dcc2df2f97.png)

According to the data, the time should actually go up to `00:59:59`.

In debugging this, i tried adding the following right after [this line](https://github.com/juttle/juttle-client-library/blob/988ee4e9621da788618f2697837bfe12309f0c67/src/utils/job-socket.js#L43):
```javascript
console.log(msg.type);
```
What I saw was a bit puzzling:
![image](https://cloud.githubusercontent.com/assets/3344137/12706147/44fcf356-c833-11e5-87b1-1d86cd1a0cc3.png)

In the screenshot, there are 8 messages with `type: "points"` but in the console, `"points"` is only printed 6 times. Additionally, the `"sink_end"` and `"job_end"` messages are never printed. So the browser is certainly receiving them according to chrome dev tools, but somehow our WebSocket `onmessage` event listener isn't seeing them before it gets the `onclose` event.

Wondering if waiting longer in outrigger to close the websocket would make the problem go away, I tried adding a 1 second setTimeout on [this line](https://github.com/juttle/outrigger/blob/17990b3d8bd79b893a2313ae7000a1cd2766f62d/lib/websocket-endpoint.js#L98) before actually closing the websocket. Sure enough, I started seeing all the messages:
![image](https://cloud.githubusercontent.com/assets/3344137/12706201/7b7263b6-c834-11e5-9a6a-879ea7b28674.png)
And as expected the timechart shows the full range:
![image](https://cloud.githubusercontent.com/assets/3344137/12706224/ccfaed66-c834-11e5-941f-37603a777c55.png)

So...a bit uncertain as to what is going on. Is outrigger closing the websocket too soon? Should we be sending back acknowledgements from the browser? The browser certainly seems to be receiving the messages, just not our WebSocket onmessage handler.

@mnibecker @mstemm, you guys have dealt with some race conditions related to websockets in outrigger/juttle-client-library...any thoughts on what could be going on here?

**Comment by mstemm** [comment]
We decided that the best + easiest workaround is to actually close the websocket connection from the server side after a short delay. That should give the browser enough time to actually read + process all datapoints before the connection close causes it to lose the final points.

**Comment by mstemm** [comment]
Filed https://github.com/juttle/juttle-engine/issues/9 to track fixing this in juttle-engine.

**Comment by mstemm** [comment]
Un-assigning this from myself as it's for the old product.
