### ISSUE TITLE
Any program logs a console error `Uncaught SyntaxError: Unexpected end of input`

### ISSUE THREAD

**Issue by dmehra** [juttle/outrigger#136]
Any time I run a program in outrigger, the javascript console contains this error:

```
Uncaught SyntaxError: Unexpected end of input

deserialize @ index.js?5c5e:99
deserialize @ index.js?46c0:24
_onMessage @ job-socket.js?0eba:76
```

The program itself does not emit an error, and appears to successfully render what I expect.

This has been a case for at least a couple of weeks, and I just realized nobody filed a bug.

**Comment by dmehra** [comment]
Additionally, the [cadvisor-influx example program](https://github.com/juttle/outrigger/tree/master/examples/cadvisor-influx) gives this console error:

```
Uncaught SyntaxError: Unexpected end of input
deserialize @ index.js?5c5e:99
deserialize @ index.js?46c0:24
_onMessage @ job-socket.js?0eba:76
bluebird.js?e366:1444 
Warning: a promise was created in a Promise.try handler but was not returned from it
    at BaseDataTarget.extend.push (eval at <anonymous> (http://docker-local:8080/assets/run-app.js:599:2), <anonymous>:24:27)
    at View.handleViewMsg (eval at <anonymous> (http://docker-local:8080/assets/run-app.js:1661:2), <anonymous>:44:41)
```

**Comment by mstemm** [comment]
Cloned as https://github.com/juttle/juttle-service/issues/53.
