### ISSUE TITLE
Should juttled internal functions throw errors or return errors?

### ISSUE THREAD

**Issue by dmehra** [juttle/outrigger#14]
(Note: what's `juttled`? - some day a part of outrigger will be pulled out into juttled.)

From @mstemm on 12/03/15:

During the PR for the juttled unit tests, oleg brought up the difference between the functions internal to juttled (e.g. "list a job", "subscribe to a job") throwing errors when the requested action can't be done, as compared to returning a false/undefined value from the function when the action can't be done.

My style leans towards returning errors, while oleg's style leans towards throwing errors. If people feel that we should be consistent and only return errors or only throw errors, we should be consistent about that.

**Comment by mstemm** [comment]
Discussed with Oleg, and while consistency is important, we probably won't undergo the work of changing everything to use one form or another, so not carrying this issue forward to juttle-service/-engine/etc.
