### ISSUE TITLE
From/to date inputs don't work across year boundary

### ISSUE THREAD

**Issue by dmehra** [juttle/outrigger#141]
If I have inputs of type 'date' to drive `-from`/`-to` in my program, it only returns data when the MM-DD of 'from' is less than MM-DD of 'to'. Looks like it's ignoring the year in the date.

This makes it impossible to query data across the year boundary.

My program is like this:
```
input from: date -label "From" -default :2016-01-01:;
input to: date -label "To" -default :2016-01-14:;

read elastic -from from -to to
// more filtering here, unrelated to the problem
```

It works fine with from = 2016-01-01 and to = 2016-01-14, I get points. But I get zero points if
from = 2015-12-31, or from = 2015-01-15, or anything in between; it does return points with 
from = 2015-01-14.

**Comment by mstemm** [comment]
Cloned as https://github.com/juttle/juttle-viewer/issues/28.
