### ISSUE TITLE
Date inputs are displayed in local time, not UTC

### ISSUE THREAD

**Issue by dmehra** [juttle/outrigger#142]
This makes life very confusing. Given a program like this:

```
input from: date -label "From" -default :2016-01-01:;
input to: date -label "To" -default :2016-01-04:;

read elastic -id "local" -from from -to to
|(
  view table;
  view timechart;
)
```

What i see in the UI are dates `From = 2015-12-31` and `To = 2016-01-03`, which are the defaults from my program, but shifted by a day due to UTC -> local TZ conversion.

But the data in table and timechart is timestamped with UTC times. Therefore, my point dated 2016-01-01 won't show up if the `From` input is set in the UI to 2016-01-01, but only if it's set to 2015-12-31.

We should do UTC everywhere (or, at some point, support local TZ everywhere) but not mix and match.

![image](https://cloud.githubusercontent.com/assets/5817365/12835288/b859286e-cb63-11e5-9ac7-22d23b11d8df.png)

**Comment by mstemm** [comment]
Cloned as https://github.com/juttle/juttle-viewer/issues/27.
