### ISSUE TITLE
Update the docker monitoring demo

### ISSUE THREAD

**Issue by dmehra** [juttle/outrigger#24]
The demo we had, using cadvisor and influx, is blocked, see PR https://github.com/juttle/outrigger/pull/23

[cadvisor support for influx 0.9](https://github.com/google/cadvisor/issues/743)  just got merged, not in official build yet, can use google/cadvisor-canary build for testing.

We could also use a different backend (say Redis instead of Influx) or use something else (REST API?) instead of cadvisor to get the docker container stats, but with 0.9 support in, this is probably unnecessary.

We also need proper support for periodic reads to the backend in "live" mode, which was hacked up with '-lag' option in the pre-open version of this demo. The real influx adapter doesn't support '-lag' so the juttle here cannot run.

When setting up the demo, de-emphasize the role of cadvisor since it's not likely to be widely known, just style is as a demo of watching docker container activity using Juttle.

**Comment by mstemm** [comment]
Mike's going to do the work of updating the demo to work with influx 0.9. Afterward I'll work on making it more container-friendly.
