### ISSUE TITLE
Display juttle errors to the user

### ISSUE THREAD

**Issue by dmehra** [juttle/outrigger#29]
When executing Juttle in outrigger, currently both syntax and runtime errors are invisible and can only be found in the http response in the network tab of your browser dev tools. This makes debugging Juttle programs rather difficult. Let's display the errors to the user.

**Comment by demmer** [comment]
This is a pretty important issue to address shortly -- the experience of editing juttle with outrigger is pretty tedious as it stands now. 

-m

**Comment by mnibecker** [comment]
We were previously blocked on unified errors from outriggerd. Now that this is squared away, we can do this.

**Comment by davidbcook** [comment]
+1
