### ISSUE TITLE
Add a juttle editor in the browser

### ISSUE THREAD

**Issue by dmehra** [juttle/outrigger#30]
For quick editing of Juttle programs (for demo purposes, and perhaps for a quick REPL cycle of development), let's add an editor in the browser. 

ACE based editor like we used to have is a fine option. Ideally it would support autocomplete. 

Displaying syntax errors as you type is not requested, it's good enough to see errors (runtime or syntax) once you click the play button to run the program.

A single editor window with a single output canvas is sufficient.

This could be supported by outrigger-client at an /edit endpoint instead of /run endpoint which executes programs from a file path.

There needs to be no allowance for saving or loading the Juttle code when using the editor. When you want to save the code, you can select it, copy to clipboard, then save in a local editor to a file however you like; the app doesn't need to handle saving.

**Comment by davidbcook** [comment]
I would LOVE this!

**Comment by mstemm** [comment]
Cloned as https://github.com/juttle/juttle-viewer/issues/29.
