### ISSUE TITLE
Add a screenshot

### ISSUE THREAD

**Issue by dmajda** [juttle/outrigger#85]
Let’s add a nice, interesting screenshot of Outrigger into `README.md`.

In my experience it’s hard to convince people to look deeper into Outrigger or try it out when they can’t see what it looks like in advance (and you don’t have a running instance handy — which is the case for all everyone browsing the repo on his/her own).

**Comment by dmehra** [comment]
How do you like this one? Not sure if better with or without visible tooltip. Ideally we'd have from/to inputs too, but not yet.

![image](https://cloud.githubusercontent.com/assets/5817365/12404726/f8b63eca-bdf2-11e5-9792-9722d5c1f974.png)

![image](https://cloud.githubusercontent.com/assets/5817365/12404740/15850d74-bdf3-11e5-8744-e580c84e427a.png)

**Comment by demmer** [comment]
Can you redo these now that https://github.com/juttle/outrigger/pull/87 has
merged?

I think the chart looks really odd as-is with the periodic price drops to 0.

I think with the tooltip is better.


On Mon, Jan 18, 2016 at 2:52 PM, Daria Mehra <notifications@github.com>
wrote:

> How do you like this one? Not sure if better with or without visible
> tooltip. Ideally we'd have from/to inputs too, but not yet.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5817365/12404726/f8b63eca-bdf2-11e5-9792-9722d5c1f974.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5817365/12404740/15850d74-bdf3-11e5-8744-e580c84e427a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juttle/outrigger/issues/85#issuecomment-172675069>.
>



-- 
Michael Demmer
Jut - CTO / VP Engineering
demmer@jut.io

**Comment by dmehra** [comment]
Fresh off master:

![image](https://cloud.githubusercontent.com/assets/5817365/12405528/dd62cd80-bdf9-11e5-993d-d9c77addde28.png)

Ok @demmer ? I'll add it to the README if that looks good.

**Comment by dmajda** [comment]
Showing also the browser window would be even nicer, it gives a sense of completeness (it’s clear that nothing is missed).

**Comment by demmer** [comment]
I agree with @dmajda -- the full browser window would be better. Of course you'll need to close your hundreds of tabs first 😉

**Comment by demmer** [comment]
Also this chart looks good but I wonder if we might want to have a couple more to show off the breadth of what is can do.

**Comment by dmehra** [comment]
Let's get this one, and I've been meaning to do a chart gallery for weeks now, when that's done i'll add it to show off the viz. Anything else you favor @demmer? Twitter looks good, but we'd be showcasing trump.
